language: ruby
services:
  - redis-server
rvm:
  - 2.1.1
  - 2.1.2
script:
- bundle exec rspec
install:
- "./rebund/run download"
- bundle install --path vendor/bundle
after_script:
- "./rebund/run upload"
env:
  global:
    secure: "kMxJcT8xyQ+QyCeKW5lDP44IU99Y8iN1AWZo9Z1BKN6HigGa8Ua8O/aD8AJjrTfRRSjnM402utmW6mk78RYVxJha3+69jJYr25I9EeyYhV2cuRu+5Ictxfcb9R9VhS0b6LDncz9h55xDS1UA35rvj+EOO4/M9moccw7T2qzPa2U="
